### ISSUE TITLE
New Model: BeeSmart HubNet

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#124]
Waiting for @toxy100 to push it to a branch. It will then need to be checked out.

**Comment by arthurhjorth** [comment]
Hi @toxy100 , how's this looking?

**Comment by toxy100** [comment]
Solved most problems, have a few questions for Nicolas, will contact him
today.
Bryan

**Comment by arthurhjorth** [comment]
Great,  thanks for getting back so quickly!

**Comment by toxy100** [comment]
just pushed the most recent changes. Still haven't figured out two things: 1. how to make the user message last longer, and 2. the end state of the model (best-chosen? should have indicated the end/winning state, when all bees decided to fly to the best hive). While 1 is more technical, 2 is more conceptual. I'll try my best to solve these today, and I look forward to Nicolas's input. But if I can't, the model may need to go with the next release...

**Comment by nicolaspayette** [comment]
> just pushed the most recent changes

Thanks! I will get on the reviewing.

> 1. how to make the user message last longer

I'll see if I can come up with something to fix that.

> 2. the end state of the model (best-chosen? should have indicated the end/winning state, when all bees decided to fly to the best hive).

I'm not sure I understand that one, but feel free to elaborate if you want to.

> But if I can't, the model may need to go with the next release... 

Given the _very_ short window that we have for 5.2.1, that's a possibility...

**Comment by toxy100** [comment]
I'll elaborate "the end state of the model (best-chosen? should have indicated the end/winning state, when all bees decided to fly to the best hive).":

Currently the model doesn't have an end state. In reality, when a certain site wins enough number of advocates, the swarm makes the decision to choose that site as their new home, which is the end of the hive-finding process. Real bees count other bees at the same site. When they feel there's enough of them on a certain site, they fly back to the swarm and stir the whole swarm to take off. I tried to achieve this by counting if all the students are simultaneously on a certain site, but it won't work because what if there is only one student? (I didn't model the taking off part of the phenomenon in this model. I just want it ends at the point when there are enough supporters for a certain site). If the students chose the best site, best-chosen? should be set to true, although it's totally possible that they chose a lower quality hive, which is also the end state of the model. 

Let me know if this is clear.

**Comment by nicolaspayette** [comment]
@toxy100 see new comments at https://github.com/NetLogo/ccl-models/pull/65.

**Comment by nicolaspayette** [comment]
I'm closing this issue. We have https://github.com/NetLogo/ccl-models/pull/67 to track the progress on this model.
