### ISSUE TITLE
Wall Following Example: cut off text in note

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#169]
<img width="203" alt="screen shot 2015-12-04 at 10 54 35 pm" src="https://cloud.githubusercontent.com/assets/161079/11605898/1c609c44-9ada-11e5-93b8-ee26e6b4815e.png">

**Comment by SethTisue** [comment]
in 5.2.2-RC2 on Mac OS X 10.11

**Comment by nicolaspayette** [comment]
Interesting. It looks OK on Linux, which is usually the platform with the widest fonts. Was it cut off in 5.2.1 as well?

**Comment by SethTisue** [comment]
it's fine in 5.2.1. I think on Mac the Oracle JDKs have different font stuff than the Apple ones did. e.g. @mrerrormessage had to fiddle with the info tab font sizing

**Comment by nicolaspayette** [comment]
There could be lots of affected models. I added a test to try to detect them: https://github.com/NetLogo/models/commit/5c5f811768a590b02abdd25544e2b7d4b268e0b8

My strategy is to calculate the width needed in Linux (since Travis runs in Ubuntu) and add a 5% buffer in the hope that it's enough to cover for wider fonts on Macs.

But I don't know if it is.

Can someone help me by checking if [this version of **Wall Following Example**](https://raw.githubusercontent.com/NetLogo/models/067a9892ef78cf7639b8b27db72ce77398dbb791/Code%20Examples/Wall%20Following%20Example.nlogo) is OK on a Mac with 5.2.2?

[Many model fail the test](https://travis-ci.org/NetLogo/models/builds/95691757), but a lot of them fail because they rely on the Note widget's wrapping behavior instead of adding manual line breaks. I'm contemplating the adoption of a "manual line breaks in Notes" policy, but I'm not sure if it's practical yet.

(If "wider fonts on Macs" turn out to be a significant problem, I may extend testing to other widget types).

**Comment by mrerrormessage** [comment]
Just a note - I didn't resize info tab font in 5.2.2. I can do a side-by-side comparison, but there isn't actually a size difference. The difference is in the boldness of the text, with the Java 6 text being slightly bolder than the Java 8 text. However, I'm pretty sure that making the Java 8 font bold would make it borderline unreadable. There may be some text properties that can be adjusted, but I think it's still quite readable and don't plan to change it unless there are cases where it the layout changes demonstrably between versions because of the text rendering changes.

**Comment by nicolaspayette** [comment]
> I didn't resize info tab font in 5.2.2. [...] I think it's still quite readable and don't plan to change it

I'm OK with that. The info tab text should reflow nicely anyway.

**Comment by SethTisue** [comment]
> I didn't resize info tab font in 5.2.2

I'm not seeing any info tab font size difference either in 5.2.2-RC2. Perhaps my original report was specific to RC1. Or perhaps I was confused about something, like I'd zoomed without realizing it? I don't know.

**Comment by mrerrormessage** [comment]
There were some pretty substantial differences ![](https://files.gitter.im/mrerrormessage/kydF/Screen-Shot-2015-11-24-at-1.54.19-PM.png). I'll give this another look today and see if there isn't some way to fix this, or whether I might have changed something in the widget code. 

Also, is there any chance this might be related to [NetLogo#899](https://github.com/NetLogo/NetLogo/pull/899)?

**Comment by mrerrormessage** [comment]
OK, on the latest build of 5.3, this is fixed. My suspicion is that the quaqua upgrade and the look and feel configuration fixed it, but it could honestly be something else entirely. 
<img width="192" alt="screen shot 2015-12-09 at 8 57 40 am" src="https://cloud.githubusercontent.com/assets/143198/11688569/09bae424-9e53-11e5-8764-015e1d132f1a.png">
I'm planning to put out a new RC later tonight (or perhaps tomorrow morning) and it would be good to test that Wall Following and any other models look alright.

**Comment by nicolaspayette** [comment]
That's with the non-revised model?

--
Nicolas
(mobile)

**Comment by mrerrormessage** [comment]
That's correct, the model has not been changed.

**Comment by nicolaspayette** [comment]
All good, then. I'll close this issue. (I'll still enforce a small buffer for notes width, though. But maybe a bit less than 5%.)
