### ISSUE TITLE
Suggestions for Awareness model

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#196]
"There is a discrete set of “levels” of awareness that people may attain. A person may be “unaware” (0 - 5 points), “aware” (5 - 10 points), “well-informed” (10 - 15 points), or an “activist” (more than 15 points)."

I wonder if this is a good idea. There are no behavioural difference between the first 3 categories. And it introduces artefacts into the graph when someone moves back and forth at a category boundary.

More seriously the way the simulation ends when every patch ends up with an information centre is just very odd. There are many more centres than people. A slightly better rule for activists starting information centres could fix this. E.g. start one only if there are only a few within some radius.

**Comment by nicolaspayette** [comment]
There is no behavioral difference between "unaware" and "aware", but there is one between "aware" and "well-informed": well-informed turtles inform others around them while those that are merely "aware" don't. (And, of course, only "activists" create "centers".)

I agree that the rule for creating information centers is very odd. But the whole behavior of the model depends on that rule: altering it would completely change the model's dynamics, and I'm reluctant to do that in a Curricular Model, since there could be papers, grant reports or curricular material that depend on that particular behavior.
