### ISSUE TITLE
Control over initialisation of Percolation model

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#197]
The Percolation model always starts with every other pixel containing oil. My student was curious how much the initial conditions mattered. I suggested he change the appropriate line of code in setup. But the model could have a slider for percentage of surface has oil.

**Comment by nicolaspayette** [comment]
That's a good suggestion... one that the EXTENDING THE MODEL section of the info tab already makes:

> Currently, the model is set so that the user has no control over how much oil will spill. Try adding a feature that will allow the user to specify precisely, when s/he presses SETUP, the amount of oil that will spill on that go. For instance, a slider may be useful here, but you’d have to modify the code to accommodate this new slider. Such control over the to-be-spilled amount of oil gives the user a basis to predict how deep the oil will eventually percolate (i.e. how many empty spaces it will fill up). But then again, the depth of the spill is related to the soil’s porosity. Can you predict the depth of the spill before you press GO?

Should it have been part of the model instead of being a suggested extension? Perhaps. But it could also be argued that making the change "by hand" is a valuable learning experience.

The same question could be asked of almost any "extending the model" suggestion in the library. Those are judgment calls that were made at the time the models were designed. I think the _status quo_ should be favored unless a very compelling case is made for revisiting the decision...

**Comment by SethTisue** [comment]
I think it's almost always best to err on the side of keeping the models small.
