### ISSUE TITLE
Recovery time not turtles-own in EpDEM Basic

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#203]
Info tab says:

AVERAGE-RECOVERY-TIME (50 - 300): The time it takes for an individual to recover on average. The actual individual’s recovery time is pulled from a normal distribution centered around the AVERAGE-RECOVERY-TIME at its mean, with a standard deviation of a quarter of the AVERAGE-RECOVERY-TIME.

The code says:

```
    ;; Set the recovery time for each agent to fall on a
    ;; normal distribution around average recovery time
    set recovery-time random-normal average-recovery-time average-recovery-time / 4
```

and yet

```
globals
[
  recovery-time         ;; Time (in hours) it takes to recover from the infection
```

To be consistent with the Info tab and the code comments recovery-time should be turtles-own

Just to add to the confusion recovery-time isn't the average time to recovery but the time when on each tick there is "recovery-chance" odds of recovering.

The Info tab says

RECOVERY-CHANCE (10 - 100): Probability of an infected individual to recover.

but that is only after infection-length > recovery-time

**Comment by ToonTalk** [comment]
Travel and Control version has the same problems

**Comment by ToonTalk** [comment]
And the comment 

susceptible-0       ;; Initial number of susceptible people

isn't right. This is a turtle variable that is either 0 or 1.

A strange but not incorrect way of computing

  ;; Initial number of susceptibles:
  let s0 sum [ susceptible-0 ] of turtles

Though as sample code it encourages a poor coding style.

**Comment by nicolaspayette** [comment]
> To be consistent with the Info tab and the code comments recovery-time should be turtles-own

Yes, that was a bug. I changed it: 544e9c3db2fd2bb14db193079f3459d3bf6babce.

> Just to add to the confusion recovery-time isn't the average time to recovery but the time when on each tick there is "recovery-chance" odds of recovering.

Right. Comment clarified: b6c45b4b5150b199adb6cc88b266becadd2b7123.

> The Info tab says
>
> > RECOVERY-CHANCE (10 - 100): Probability of an infected individual to recover.
>
> but that is only after infection-length > recovery-time

True. Clarified in 633c463c9385cf1ee61cacf6ee2ed2a9360227e0.

> And the comment
> ```
> susceptible-0       ;; Initial number of susceptible people
> ```
> isn't right. This is a turtle variable that is either 0 or 1.
>
> A strange but not incorrect way of computing
> ```
>  ;; Initial number of susceptibles:
>  let s0 sum [ susceptible-0 ] of turtles
> ```
> Though as sample code it encourages a poor coding style.

Agreed. I changed it to a boolean: ff7959e022ebdfcff354946a94ffcbc8516b2de8.

@ckycky, those were originally your models. You may want to double-check the changes.

Also, in the **Travel and Control** version, "ambulance" should have been a breed instead of a boolean turtle variable: the current code is full of `if ambulance?` and `if not ambulance?` checks that complicate things and increase the risk of errors.
