### ISSUE TITLE
Confusing explanation in Wealth Distribution Info Tab

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#207]
When I read

> Another way to understand the Lorenz curve is to imagine that there are 100 dollars of wealth available in a society of 100 people. Each individual is 1% of the population and each dollar is 1% of the wealth. Rank the individuals in order of their wealth from greatest to least: the poorest individual would have the lowest ranking of 1 and so forth. 

I imagined that if someone has an extra dollar then someone else has zero dollars. Probably not the image one wants to convey. Talking about 100 dollars and 100 people is the problem. Maybe 100 people and a million dollars would avoid this confusion.

**Comment by nicolaspayette** [comment]
> Talking about 100 dollars and 100 people is the problem. Maybe 100 people and a million dollars would avoid this confusion.

The original intention of the person who wrote the info tab was probably to make use of the 1$ = 1% equivalence like they do with the 1 person = 1% equivalence... but they didn't end up using it anywhere (which is a bit confusing because, when reading, you sort of expect it to play a role).

I think we're better off not mentioning a specific amount:

> Another way to understand the Lorenz curve is to imagine a society of 100 people with a fixed amount of wealth available.  Each individual is 1% of the population. Rank the individuals in order of their wealth from greatest to least: the poorest individual would have the lowest ranking of 1 and so forth.
