### ISSUE TITLE
Missing screenshots 5.2

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/models#29]
@frankduncan sent this list:

MISSING PREVIEW: 3D/Sample Models/Hydrogen Diffusion 3D.png
MISSING PREVIEW: Code Examples/Palette Example.png
MISSING PREVIEW: Curricular Models/ModelSim/Evolution/Bacteria Food Hunt.png
MISSING PREVIEW: Curricular Models/ModelSim/Evolution/Bacteria Hunt Speeds.png
MISSING PREVIEW: IABM Textbook/chapter 0/Turtles Circling Simple.png
MISSING PREVIEW: IABM Textbook/chapter 5/Agentset Efficiency.png
MISSING PREVIEW: IABM Textbook/chapter 5/Random Network.png
MISSING PREVIEW: IABM Textbook/chapter 8/Arduino Example.png
MISSING PREVIEW: IABM Textbook/chapter 8/Disease With Android Avoidance HubNet.png
MISSING PREVIEW: IABM Textbook/chapter 8/Example HubNet.png
MISSING PREVIEW: Sample Models/Social Science/Unverified/Artificial Anasazi.png

**Comment by nicolaspayette** [comment]
Checking in all these PNGs was an acceptable quick fix for the release, but ideally, for each model, we should either:

- put in custom preview commands and remove the image from the repo, or
- put in `:need-to-manually-make-preview-for-this-model` in the model file.

Re-opening. I'll take care of sorting it up.

**Comment by SethTisue** [comment]
Nicolas already knows, but just for the record, this isn't only about having nice images. It's really important for the continued health of NetLogo to have working preview commands in as many models as possible, because the preview commands are also the basis of the model checksums tests, which (along with the language tests) are one of the two main pillars of our testing regime, that not only guards against regressions in JVM NetLogo, but also helps ensure that Tortoise and JVM NetLogo behave the same.
