### ISSUE TITLE
Duplicates between book models and sample models: El Farol and DLA Simple

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#40]
As in #39, our `"every model has a unique name"` fails for two book models that have duplicates under the `Sample Models` folders:

- `IABM Textbook/chapter 3/El Farol Extensions/El Farol` vs.
`Sample Models/Social Science/El Farol`
- `Sample Models/Chemistry & Physics/Diffusion Limited Aggregation/DLA Simple` vs.
`IABM Textbook/chapter 3/DLA extensions/DLA Simple`

The versions have already started to diverge: some minor improvements that were made in the book versions were not made in the sample models versions. The other difference is that the book versions have the ACKNOWLEDGMENT section and book specific HOW TO CITE in their info tabs.

Should we:

1. Rename one of the versions, for each model.
2. Use the book versions in the Sample Models folder.

In the name of fighting entropy, I advocate 2.

@UriCCL, what do you think?

**Comment by arthurhjorth** [comment]
I am very much in favor of 2 too. Particularly since the book versions are
better versions of the old models.

- Arthur

-- 
Arthur Hjorth
PhD Student, Learning Sciences
Center for Connected Learning <http://ccl.northwestern.edu/>
Northwestern University

e: arthur.hjorth@u.northwestern.edu
s: arthurhjorth
m: +1 (773) 943-0013

**Comment by nicolaspayette** [comment]
@UriCCL agreed with 2 as well. I made the changes. All that is left is for @frankduncan to review and merge https://github.com/NetLogo/NetLogo/pull/749.
